---
# Install the Azure CLI
# Based on <https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest>

- name: Get packages needed for the install process
  apt:
    name:
      - aptitude
      - curl
      - apt-transport-https
      - lsb-release
      - gnupg
    state: present
    update_cache: yes

- name: Import the Microsoft signing key into apt
  apt_key:
    url: "https://packages.microsoft.com/keys/microsoft.asc"
    state: present

- name: Add the Azure CLI software repository
  apt_repository:
    repo: "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ {{ansible_distribution_release}} main"
    filename: "azure-cli"
    state: present

- name: Install Azure CLI
  apt:
    name: "azure-cli"
    update_cache: yes

- name: Update all packages
  apt:
    upgrade: dist
...
